import Head from "next/head";
import { Inter } from "next/font/google";

import { useAccount, ConnectButton } from "@web3modal/react";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { account, isConnected } = useAccount();
  console.log("🚀 ~ file: index.js:10 ~ Home ~ account:", account);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div>{!isConnected && <ConnectButton />}</div>
        </div>
      </main>
    </>
  );
}
